jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout src repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_EDITORCONFIG: true
      name: Lint code base
      uses: github/super-linter@v6
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B verify --file pom.xml
name: Check Pull request
on:
  repository_dispatch:
    types: trigger-ga___pull_request.yml
